### ISSUE TITLE
zadd

### ISSUE THREAD

**Issue by kevleyski** [sagiegurari/simple_redis#18]
### Feature Description
I was hoping to be able to handle ordered sets/lists is this possible/and or easy to add myself?

### Describe The Solution You'd Like
Example - similar to sadd, call zadd with score (or score omitted for redis default lexigraphical sort)

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
@kevleyski I just pushed to a dev branch 2 new functions for zadd and zrange.
You can install from git and check if it works well for your use case.
if you look how i implemented, basically you can run any command with any args you want the same way without my wrappers but i admit having a wrapper makes it much more type safe and readable so feel free to ask for more changes.

**Comment by kevleyski** [comment]
Great thanks!

**Comment by kevleyski** [comment]
Working fine thank you

**Comment by sagiegurari** [comment]
thanks for the feedback, this is now released in 0.5.4 version
